apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/totterman/cns-dispatcher-service/k8s?ref=main

configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: dispatcher-config

images:
- name: dispatcher-service
  newName: ghcr.io/totterman/dispatcher-service
  newTag: latest

replicas:
- count: 2
  name: dispatcher-service

patches:
- path: patch-env.yml
