apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/totterman/cns-catalog-service/k8s?ref=main

configMapGenerator:
- behavior: merge
  files:
  - application-staging.yml
  name: catalog-config

images:
- name: catalog-service
  newName: ghcr.io/totterman/catalog-service
  newTag: latest

replicas:
  - name: catalog-service
    count: 2

patches:
- path: patch-env.yml
